server:
  port: 8080
  tomcat:
    max-swallow-size: 500MB
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: mymerit
      port: 27017
      host: localhost
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: a446935ece96249d5d22
            client-secret: d3e879cd7a0d6c81e6d94f7075edc49f0e08d964
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          google:
            client-id: 899578246174-akvbo1tf5lkhpdauisvbivc3unn5oljn.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 105MB
  thymeleaf:
    prefix: classpath:/template/email/
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
mymerit:
  app:
    jwtSecret: "tw1oqyxkbjg1bmgn5ociiasmdo41xg3qx5q88w19scmazo90nfjslmxdsmgkzy04i3aicwgbjtyesrftnby9wwj3ydey3g6zegh1cjk9wgov5rvwb7zafxgn74ooebz0"
    jwtExpirationMs: "172800000"
app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:5173/oauth2/redirect
springdoc:
  swagger-ui:
    path: /swagger-ui
